#!/bin/bash


# Copyright 2022 Anagnostakis Ioannis <rizitis@gmail.com> GR 
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  Before you run this script read README !!! 

slpkg -q libgusb \
colord \
gnome-desktop \
geocode-glib \
libdaemon \
blocaled \
avahi \
geoclue2 \
libgweather \
gnome-settings-daemon \
zenity \
mutter \
cogl \
clutter \
clutter-gtk \
clutter-gst \
cheese \
colord-gtk \
gnome-bluetooth \
gsound \
libhandy \
xdg-dbus-proxy \
libwpe \
wpebackend-fdo \
bubblewrap \
webkit2gtk \
rest \
gnome-online-accounts \
gnome-control-center \
libgdata \
libgweather4 \
evolution-data-server \
gnome-autoar \
gnome-shell \
gnome-session \
gdm \
gnome-tweaks \
libportal \
tracker \
nautilus \
gnome-menus \
gnome-shell-extensions \
jq \
p7zip \
chrome-gnome-shell \
gnome-backgrounds \
lxml \
yelp-xsl \
yelp-tools \
yelp \
gnome-terminal \
gnome-system-monitor \
gnome-weather \
gnome-disk-utility \
baobab \
simple-scan \
libdazzle \
gnome-calendar \
gtksourceview4 \
gnome-calculator \
libpeas \
gedit \
exempi \
libgxps \
libiptcdata \
osinfo-db-tools \
osinfo-db \
libosinfo \
totem-pl-parser \
tracker-miners \
evince \
gspell \
cmark \
libpst \
lua \
highlight \
ytnef \
libchamplain \
evolution \
file-roller \
telepathy-glib \
folks \
gnome-maps \
grilo \
gfbgraph \
gnome-photos \
gnome-screenshot \
seahorse --add
